// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABnMg83_sAmB5MqqSVFqTEKmxXKJh072s',
    appId: '1:984380938437:web:925a2e63c5f8f0005978ac',
    messagingSenderId: '984380938437',
    projectId: 'game-center-b4d5c',
    authDomain: 'game-center-b4d5c.firebaseapp.com',
    storageBucket: 'game-center-b4d5c.firebasestorage.app',
    measurementId: 'G-2VEK5DK5B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBesk2gg9aNYs7Y6STuLrzHtDIv4vZmTRk',
    appId: '1:984380938437:android:4493ae4cf88fc12b5978ac',
    messagingSenderId: '984380938437',
    projectId: 'game-center-b4d5c',
    storageBucket: 'game-center-b4d5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDulKsNwIR79TXpghMiD3CRnMvRmCpVKC0',
    appId: '1:984380938437:ios:868032c962391f2c5978ac',
    messagingSenderId: '984380938437',
    projectId: 'game-center-b4d5c',
    storageBucket: 'game-center-b4d5c.firebasestorage.app',
    iosBundleId: 'com.example.gameCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDulKsNwIR79TXpghMiD3CRnMvRmCpVKC0',
    appId: '1:984380938437:ios:868032c962391f2c5978ac',
    messagingSenderId: '984380938437',
    projectId: 'game-center-b4d5c',
    storageBucket: 'game-center-b4d5c.firebasestorage.app',
    iosBundleId: 'com.example.gameCenter',
  );
}